/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import communication.SendCommand;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Hugo Neves
 */
public class kitchenPanelInfo extends javax.swing.JPanel {
    
    public void setTemp(){
        SendCommand sc = new SendCommand("main");
        while (true) {            
            ArrayList<Object> command = new ArrayList<>();
            command.add("getCurrentTempValue");
            tempLabel.setText("Temperatura: " + sc.sendCommand("127.0.0.1", 2000, command) + "º");
                try {
                    Thread.sleep(5000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(roomPanelInfo.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
    }
    
    public void setHum(){
        SendCommand sc = new SendCommand("main");
        while (true) {            
            ArrayList<Object> command = new ArrayList<>();
            command.add("getCurrentHumValue");
            humLabel.setText("Humidade: " + sc.sendCommand("127.0.0.1", 2001, command) + "%");
                try {
                    Thread.sleep(5000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(roomPanelInfo.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
    }
    
    public kitchenPanelInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tempLabel = new javax.swing.JLabel();
        humLabel = new javax.swing.JLabel();

        tempLabel.setText("Temperatura: 00º");

        humLabel.setText("Humidade: 00%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tempLabel)
                    .addComponent(humLabel))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tempLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(humLabel)
                .addContainerGap(250, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel humLabel;
    private javax.swing.JLabel tempLabel;
    // End of variables declaration//GEN-END:variables
}
